language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - pip install codecov
install:
  - pip install .
# command to run tests
script: nosetests --with-coverage --cover-package pylend
after_success:
  - codecov